/** @format */

const names = [
  'Renude',
  'The Mukatots',
  'Snazzy Jacket',
  'Cocaine Toenail',
  'The Desert Eagles',
  'Forepause',
  'Cherish',
  'The Organics',
  'Eeklektik',
  'Ergot',
  'Platituudz',
  'Stasis',
  'Nadir',
  'Annex',
  'Specks',
  'Event Horizon',
  'Planck',
  'Concrete',
  'Ink Magick',
  'Sabotage',
  'Nymphomania',
  'Barstül',
  'Lolita',
  'Whodunit',
  'Gravitas',
  'Bedlam',
  'Rube',
  'Ennui',
  'Shallow Copy',
  'Deep Copy',
  'In Tent City',
  'Soul Stampede',
  'Fine Mist',
  'Okay Pyro',
  'Gazebo',
  'Carcass',
  'Squint',
  'Idems',
  'Pigsty',
  'Nympho',
  'Scuzz',
  'Rogue Species',
  'Glib',
  'Dead Suits',
  'Candy Lineup',
  'Gonopore',
  'Selastica',
  // 'ChromoSoWhat?',
  'Hypervisor',
  'Pop Filter',
  'Vittle',
  'Bottulnex',
  'Jackfruit',
  'Hot Mayo',
  'Theora',
  'Vorbis',
  "At Once",
  "Syntactic",
  "Soppy",
  "Trolley",
  "Somatic",
  "Leyland Cypress",
  "Pocket Chocolate",
  "Lizard Violence",
  "Sterling 925",
  "Pragma",
  "Venge Fool",
  "Teardown",
  "Binder",
  "Interrobang",
  "Mainframe",
  "Minus",
  "Shebang",
  "Mousetrap",
  "Glyph",
  "Blackberry Killers",
  "Broken Falls",
  "Madscience",
  "Silver Pillar",
  "Alter Ego",
  "Sedition",
  "Krill",
  "Baleen",
  "Rare Bloom",
  "Aria / The Arias",
  "Cornerstone",
  "Pity Sex",
  "Tanzie / Tanzi / Tansy",
  "Bedside Manor",
  "Cheap Tint",
  "Vanilla Promise",
  "Sintacks",
  "Perlin Noise",
  "Perlin Worms",
  "Rosehips",
  "Raining April",
  "Atlatl",
  "Atomic Slice",
  "Rolling, Stoned",
  "Kitty Corner",
  "Weather Pending",
  "Fallujah",
  "Young 100",
  "Sir Real",
  "Cruise Control",
  "Kidd Fire",
  "Mental Defective",
  "Mind's Eye",
  "Drunken Youth",
  "403 (Forbidden)",
  "Eclectic",
  "Loveless Union",
  "Psychofrantic",
  "Sycophantic",
  "Ivory Orphan",
  "Collective Effective",
  "Serif / The Seriffs",
  "Sun Rhythm",
  "Verruco",
  "Dangerous, Beautiful",
  "Protocall",
  "2lips",
  "Ginger Tinge",
  "Acute Strangle",
  "(If) Need Be",
  "Rolling Rocks",
  "Big Picture",
  "Megahigh Maniac",
  "Altar Ego",
  "Psycho Circus",
  "Skip Control",
  "Skip Ctrl",
  "Solo Dance Party",
  "Robin Steel",
  "Lamprey",
  "Rhodopsin",
  "Lamborghini Destiny",
  "The Sex Pretzels",
  "Lizard Brain",
  "Saboteur",
  "Dead Cat Bounce",
  "Nonsense",
  "Almost Bloodless",
  // "Crushed Cookie",
  "Cookie Crush",
  "Famous Love Blink",
  "Vitriol",
  "Deathbed",
  "Nasty Queen",
  "Karma",
  "Boiling Clouds",
  "Tortoise Mayhem",
  "Deserve Before Demand",
  "Total E",
  "Bunker Punch",
  "Hence The Scent",
  "Oklay",
  // "Brokebad Mountain",
  "The Broken Bad",
  "Roll the R",
  "Ulterior Motíf",
  "Node",
  "No'd",
  "Formant",
  "Stammer",
  "Abtruse",
  "Father's Funeral",
  "Calibrrr",
  "Scapegoat",
  "Stûmblebee",
  "Duelity",
  "Duo",
  "Devil's Advocate",
  "Media",
  "Trilemma",
  "Primal Yawp",
  "Slightly Stoned",
  "Euclidean Kale",
  "Hyperbolic Kale",
  "No Residue",
  "Boiling Rocks",
  "Gallows Humor",
  "Cartoon",
  "Dystopia",
  "Bias",
  "Aphid Bee Moth",
  "Metell",
  "Bad Temptation",
  "My Last One",
  "Ego Deaf",
  "Triple Aluminum",
  "Espionaj",
  "zer0 day",
  "Polymath",
  "Christ Consciousness",
  "Eagerly Zeroed",
  "Cravat",
  "Siklik",
  "Acid Tone",
  "Agora",
  "Unsliced Phrase",
  "Shame",
  // "HODL",
  // "Doppler / Dopplr",
  "Dopplr",
  "Night Light",
  "Psychocillibeans",
  "Spaghetti Western",
  "Total Exuberance",
  "Voltare",
  "Upturn",
  "FOMO",
  // "Raspberry Blow",
  "Damn, Darling",
  "Absinthe",
  "Siko",
  "X10U8 (extenuate)",
  "Reserv3",
  "Tryptamine",
  "Shulgin",
  "Fear & Loathing",
  // "Beer & Clothing",
  "Dialect / Die Elect",
  "Fi",
  "Medium-Fi",
  "BiFi",
];

let notAccessed = [];
const randomValueFromArray = (myArray) => {
  if (notAccessed.length === 0) {
    for (let i = 0; i < myArray.length; i++) notAccessed.push(i);
  }
  let randomIndex = Math.floor(Math.random() * notAccessed.length);
  let indexOfItem = notAccessed[randomIndex];
  notAccessed.splice(randomIndex, 1);
  return myArray[indexOfItem];
};

function newBandName() {
  // const randomNumber = Math.floor(Math.random() * names.length);
  const nameDisplay = document.getElementById("nameDisplay");
  const mainCard = document.getElementById("mainCard");
  nameDisplay.innerHTML = randomValueFromArray(names);
  mainCard.style.display = "block";
}

function changeButtonText() {
  const newNameButton = document.getElementById("newNameButton");
  if (newNameButton.innerText !== "Suggest another name!") {
    newNameButton.innerText = "Suggest another name!";
  }
}
