const names = [
'Sedition',
'Krill',
'Baleen',
'Rare Bloom',
'Aria / Arias',
'Cornerstone',
'Pity Sex',
'Tanzie / Tanzi / Tansy / Tan-Z',
'Bedside Manor',
'Cheap Tint',
'Vanilla Promise',
'Sintax / Sintacks',
'Perlin Noise',
'Perlin Worms',
'Rosehips',
'Raining April',
'Atlatl',
'Atomic Slice',
'Rolling, Stoned',
'Kitty Corner',
'Weather Pending',
'Fallujah',
'Young 100',
'Sir Real',
'Cruise Control',
'Kidd Fire',
'Mental Defective',
'Mind\'s Eye',
'Drunken Youth',
'403 (Forbidden)',
'Eclectic',
'Loveless Union',
'Psychofrantic',
'Sycophantic',
'Ivory Orphan',
'Collective Effective',
'Serif / Seriffs',
'Sun Rhythm',
'Verruco',
'Dangerous, Beautiful',
'Protocall',
'2lips',
'Ginger Tinge',
'Acute Strangle',
'(If) Need Be',
'Rolling On Rocks / Roll On Rocks',
'Big Picture',
'Megahigh Maniac',
'Altar Ego',
'Psycho Circus',
'Skip Control / Skip Ctrl',
'Solo Dance Party',
'Robin Steel',
'Lamprey',
'Rhodopsin',
'Lamborghini Destiny',
'The Sex Pretzels',
'Lizard Brain',
'Saboteur',
'Dead Cat Bounce',
'Nonsense',
'Almost Bloodless',
'Crushed Cookie',
'Cookie Crush',
'Famous Love Blink',
'Vitriol',
'Deathbed',
'Nasty Queen',
'Karma',
'Boiling Clouds',
'Tortoise Mayhem',
'Deserve Before Demand',
'Total E',
'Bunker Punch',
'Hence The Scent',
'Oklay',
'Brokebad Mountain',
'Broken Bad',
'Roll the R',
'Ulterior Motíf',
'Node',
'No\'d',
'Formant',
'Stammer',
'Abtruse',
'Father\'s Funeral',
'Calibrrr',
'Scapegoat',
'Stûmblebee',
'Duelity',
'Duo',
'Devil\'s Advocate',
'Media',
'Trilemma',
'Primal Yawp',
'Slightly Stoned',
'Euclidean Kale',
'Hyperbolic Kale',
'No Residue',
'Boiling Rocks',
'Gallows Humor',
'Cartoon',
'Dystopia',
'Bias',
'Aphid Bee Moth',
'Metell',
'Bad Temptation',
'My Last One',
'Ego Deaf',
'Triple Aluminum',
'Espionaj',
'zer0 day',
'Polymath',
'Christ Consciousness',
'Eagerly Zeroed',
'Cravat',
'Siklik',
'Acid Tone',
'Agora',
'Unsliced Phrase',
'Shame',
'HODL',
'Doppler / Dopplr',
'Night Light',
'Psychocillibeans',
'Spaghetti Western',
'Total Exuberance',
'Voltare(Voltaire)',
'Upturn',
'FOMO',
'Raspberry Blow',
'Damn, Darling',
'Absinthe',
'Siko',
'X10U8',
'Reserv3',
'Tryptamine',
'Shulgin',
'Fear & Loathing',
'Beer & Clothing',
'Dialect / Die Elect',
'Fi / Medium-Fi / BiFi',
];

let notAccessed = [];
const randomValueFromArray = (myArray) => {
  if (notAccessed.length === 0) {
    for (let i = 0; i < myArray.length; i++) notAccessed.push(i);
  }
  let randomIndex = Math.floor(Math.random() * notAccessed.length);
  let indexOfItem = notAccessed[randomIndex];
  notAccessed.splice(randomIndex, 1);
  return myArray[indexOfItem];
}

function newBandName() {
  // const randomNumber = Math.floor(Math.random() * names.length);
  const nameDisplay = document.getElementById('nameDisplay');
  const mainCard = document.getElementById('mainCard');
  nameDisplay.innerHTML = randomValueFromArray(names);
  mainCard.style.display = 'block';
}

function changeButtonText() {
  const newNameButton = document.getElementById('newNameButton');
  if (newNameButton.innerText !== "Suggest another name!") {
    newNameButton.innerText = "Suggest another name!" ;
  }
}